// Generated by https://quicktype.io

export interface Routine {
    id?: number | null;
    name?: string | null;
    id_user?: string | null;
    is_default?: boolean | null;
    muscle?: string | null;
    desc?: string | null;
    image?: string | null;
}
